name: test-suite
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install ZFS
      run: |
        sudo apt-get update
        sudo apt-get install -y zfsutils-linux
    - name: Create zpool
      run: |
        truncate --size 1G disk-image
        sudo zpool create test-pool /home/runner/work/zfs_uploader/zfs_uploader/disk-image
    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test suite
      run: |
        python -m unittest
